/* eslint-disable prettier/prettier */

export const jwtSecret="eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcxNDYwNDc4NCwiaWF0IjoxNzE0NjA0Nzg0fQ.ADYgsIZBR60GxTy7HOtnAJin0jNi7ekVNE5imayVR4k";
